server:
  port: ${port} #服务端口 启动时动态传入实现高可用

spring:
  application:
    name: my-microservice-eureka #指定服务名

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: ${eureka.server}  #启动时动态传入实现高可用 查询服务和注册服务都需要依赖这个地址
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
  server:
    enable-self-preservation: false #禁用自我保护模式
    eviction-interval-timer-in-ms: 60000 #清理间隔（单位毫秒，默认是60*1000）

#security:
#  basic:
#    enable: true #开启基于HTTP basic的认证
#  user: #配置用户的账号信息
#    name: meng
#    password: 1234
logging:
  level:
    root: debug
  #    org.springframework.web: DEBUG
  file: /log/log/my_eureka.log
  pattern:
    console: "%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n"
#logging.level.root=WARN
#logging.level.org.springframework.web=DEBUG
#logging.file=/log/log/my.log
#logging.pattern.console=%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n
#logging.pattern.file=%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n